---
- name: Create AWS Infrastructure
  hosts: localhost
  connection: local

  tasks:

    - name: Create Database VM
      include_role:
        name: azure
      vars:
        az_environement: "{{ scope }}"
        az_application: database

  
    - name: Create EAP VMs
      include_role:
        name: azure
      vars:
        az_environement: "{{ scope }}"
        az_application: eap
